  - alias: Turn on light before sun sets
    trigger:
      - platform: sun
        event: sunset
        offset: "-01:20:00"
    action:
      service: scene.turn_on
      entity_id: scene.kvall
  - alias: Turn off after sun rise
    trigger:
      - platform: sun
        event: sunrise
        offset: "01:00:00"
    action:
       service: scene.turn_on
       entity_id: scene.slack_allt 
  - alias: Check sensor value and show notification
    trigger:
      platform: numeric_state
      entity_id: sensor.grunden_2_humidity
      above: 75
    action:
      service: notify.ola
      data:
        message: "Kontrollera avfuktare"
  - alias: Turn on light hallway
    trigger:
      platform: sun
      event: sunset
      offset: "-02:00:00"
    action:
      service: scene.turn_on
      entity_id: scene.hall
  - alias: Turn on dryer
    trigger: 
      platform: numeric_state
      entity_id: sensor.grunden_humidity
      above: 75
    action:
      service: switch.turn_on
      entity_id: switch.avfuktare
  - alias: Turn off dryer
    trigger: 
      platform: numeric_state
      entity_id: sensor.grunden_humidity
      below: 67
    action:
      service: switch.turn_off
      entity_id: switch.avfuktare
  - alias: MQTT test
    trigger:
      platform: mqtt
      topic: hass/test
      payload: 'hej'
    action:
      service: switch.turn_on
      entity_id: light.ceiling